package com.giga.nexas.transfer.bhe2bsdx.mapappend.composition;

public enum MapCompatibilityBlockingReason {
    NOT_MULTIPLE_SPRITE_MAP_LIST,
    MISSING_SOURCE_SPM,
    SPM_PARSE_FAILURE,
    MISSING_GROUP_INDEX,
    GROUP_INDEX_OUT_OF_SPRITE_MAP_LIST_RANGE,
    MISSING_TYPE_ID,
    TYPE_ID_OUT_OF_SOURCE_SPM_RANGE,
    INVALID_CHIP_IMAGE_REFERENCE,
    INVALID_PAT_PAGE_REFERENCE,
    MISSING_RESOURCE_REWRITE,
    MISSING_FINAL_REFERENCE,
    MISSING_TARGET_TEXT
}
